[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "topojson"
author = "Mattijn van Hoek"
author-email = "mattijn@gmail.com"
home-page = "https://github.com/mattijn/topojson"
requires = ["numpy", "shapely", "simplification"]
keywords = "topojson python github topology geojson"
description-file = "README.md"
classifiers = ["License :: OSI Approved :: BSD License"]

[tool.flit.metadata.requires-extra]
test = ["unittest"]
dev = ["geojson", "geopandas"]

